name: Deploy to github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clean install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Run deploy script
        run: yarn deploy